apiVersion: v1
kind: Service
metadata:
  name: ms2-service
spec:
  selector:
    app: ms2
  ports:
    - port: 5000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms2-depl
spec:
  selector:
    matchLabels:
      app: ms2
  template:
    metadata:
      labels:
        app: ms2
    spec:
      containers:
        - name: ms2
          image: ms2:1.0.0
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
